version: '3'

services:
  db:
    image: postgres
    env_file: .env    
    volumes:
      - postgres:/data/postgres
      - .:/code
    ports:
      - "5432:5432"
    networks:
      - postgres

  pgadmin:
    container_name: docker_django_pgadmin_container
    image: dpage/pgadmin4
    env_file: .env 
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    depends_on:
      - db

  web:
    build: .  
    entrypoint: ["./wait-for-postgres.sh"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    networks:
      - postgres
    depends_on:
      - db

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin: